image: registry.gitlab.com/epita-image/docker/cpp/staging:add-git

stages:
    - build
    - tests

build:all:
    stage: build
    before_script:
        - mkdir build
        - cd build
    script:
        - cmake .. && make
    artifacts:
        paths:
            - build
        untracked: true

.unit-tests:
    stage: tests
    script:
        - ./build/tests/${module_name}/tests
    dependencies:
        - build:all

unit-tests:math:
    extends: .unit-tests
    variables:
        module_name: "math"
