image: registry.gitlab.com/epita-image/docker/cpp:latest

stages:
    - build
    - tests
    - doc
    - check
    - snapshot

variables:
    SNAPSHOT_DIRECTORY: "snapshot_${CI_COMMIT_SHA}"

build:all:
    stage: build
    before_script:
        - mkdir build
        - cd build
    script:
        - cmake -DCMAKE_BUILD_TYPE=RELEASE -DENABLE_TESTING=1 .. && make
    artifacts:
        paths:
            - build
        untracked: true

unit-tests:all:
    stage: tests
    script:
        - make test -C build
    dependencies:
        - build:all

upload:doc:
    stage: doc
    dependencies:
        - build:all
    script:
        - make doc -C build
        - mv doc/html/ public/
    artifacts:
        paths:
            - public

render:snapshot:
    stage: snapshot
    dependencies:
        - build:all
    before_script:
        - mkdir "${SNAPSHOT_DIRECTORY}"
    script:
        - ./build/src/photonizer samples/cornell.json map -p 10000 -b 10
        - ./build/src/photonizer samples/cornell.json trace ${SNAPSHOT_DIRECTORY}/vanilla.ppm
        - ./build/src/photonizer samples/cornell.json trace -m photons.pht -c 300 -r 1 photonized.ppm
    artifacts:
        paths:
            - ${SNAPSHOT_DIRECTORY}
