image: registry.gitlab.com/epita-image/docker/cpp:latest

stages:
    - build
    - tests
    - doc
    - check

build:all:
    stage: build
    before_script:
        - mkdir build
        - cd build
    script:
        - cmake -DCMAKE_BUILD_TYPE=RELEASE -DENABLE_TESTING=1 .. && make
    artifacts:
        paths:
            - build
        untracked: true

unit-tests:all:
    stage: tests
    script:
        - make test -C build
    dependencies:
        - build:all

upload:doc:
    stage: doc
    dependencies:
        - build:all
    script:
        - make doc -C build
        - mv doc/html/ public/
    artifacts:
        paths:
            - public

clang-tidy:all:
    stage: check
    script:
        - find src -name '*.cc' -exec clang-tidy -header-filter='.*' {} -- -Isrc -std=c++17 \;
