image: registry.gitlab.com/epita-image/docker/cpp:latest

stages:
    - build
    - tests
    - check

build:all:
    stage: build
    before_script:
        - mkdir build
        - cd build
    script:
        - cmake .. && make
    artifacts:
        paths:
            - build
        untracked: true

.unit-tests:
    stage: tests
    script:
        - ./build/tests/${module_name}/tests
    dependencies:
        - build:all

unit-tests:math:
    extends: .unit-tests
    variables:
        module_name: "math"

clang-tidy:all:
    stage: check
    script:
        - find src -name '*.cc' -exec clang-tidy -header-filter='.*' {} -- -Isrc -std=c++17 \;
