image: registry.gitlab.com/epita-image/docker/cpp:latest

stages:
    - build
    - tests
    - doc
    - check
    - snapshot

variables:
    SNAPSHOT_DIRECTORY: "snapshot_${CI_COMMIT_SHA}"

build:all:
    stage: build
    before_script:
        - mkdir build
        - cd build
    script:
        - cmake -DCMAKE_BUILD_TYPE=RELEASE -DENABLE_TESTING=1 .. && make
    artifacts:
        paths:
            - build
        untracked: true

render:snapshot:
    stage: snapshot
    dependencies:
        - build:all
    before_script:
        - mkdir "${SNAPSHOT_DIRECTORY}"
    except:
        - branches
    only:
        - master
    script:
        - PHOTONIZER_RESOURCES=$(pwd)/samples/meshes ./build/src/photonizer samples/cornell.json map -p 10000 -b 10
        - PHOTONIZER_RESOURCES=$(pwd)/samples/meshes ./build/src/photonizer samples/cornell.json trace ${SNAPSHOT_DIRECTORY}/vanilla.ppm
        - PHOTONIZER_RESOURCES=$(pwd)/samples/meshes ./build/src/photonizer samples/cornell.json trace -m photons.pht -c 300 -r 1 ${SNAPSHOT_DIRECTORY}/photonized.ppm
    artifacts:
        paths:
            - ${SNAPSHOT_DIRECTORY}
